# Generated by Django 2.2.4 on 2019-08-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfcreator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='name',
            new_name='donor_name',
        ),
    ]
